dist: trusty
language: node_js
node_js:
- '10'
before_install:
- npm install
deploy:
  app: cloudpt
  provider: heroku
  api_key:
    secure: ohACGG8xV52ZeHL8FGtiF6jny6zvZeCQ2r6efudlNAoDVgQKw6ZdFY46rC9L5cPbOMqTbPfIzUXg2WLUYs/oTGtmzhuvXOu6gBkhbyOMlbgLe/suPjWcwSDBYc8r1d+UoLnAM++KtcyIiGuqTkvFOwOMLJX7m3zgUbge5zSRNVr/48/XkB/P3GTs+DX2B/WH9Nshze4OyFrXhYIwkBoB6YHYiqkh0tgmWYDDDQAu2q1EscwxPI2eWGrnk/y4RzS6dBt7hgjQht0EZybj/q6v6TLtLUsORBnlapimTb+TWl2BMWhcCN/GhSkVRHZqWDEhI5WFdhAeeMzYP8akuiNCwmyqY1lTeUM4VqXcLyRwm1i23fDHnsq6iW8BoHJz0Rf9wtpQTC047mhmUTn2xGvPJybIhyAk77m5N7TRX+QmJwlL53yFxxzj7wx/9/H+H+JDOubAhC5SrKANWSlF6FK8wW97Sqah3D+SKlrEZl4mhdshpoKeZkObc1XA0pEM7Jwwo77kP5nIq93+eNOjpwbuWFCuIUH3snmbu9tZuBRpEUU8ToKludKk6Qd5dnmJdu5TVfeD0mSB92HRI5IRplw2dgSvaKQEw6FgduQsuPbSFkl1lTxhabB36BQGIZg64XGk8k0a4p3YavjJaYMe50Df9EvKWAk2yUpudDmKWhYBSMU=
env:
  global:
    secure: gxXEfvQcrvxMSPUpkX/4pukMcjF3jeh/DiMnPkSnTNvO31ag33AczfPv9yFTceo2y4eH0o1zGwZ6xrZschHc3048FY9Ksevp884XSWiKwl9kq9AnDbz8p5L338ppVjPbB9IbnYvcrZQO+SbMrK22wmMV76cZjobXgc+01ypKfvYQyPvsUxC3Vx115e7WE1oclyilNlC3Lkc4ZzL/kO+6u8CimrOgs1w/7o9YZZtjtyxP2aU6iKpjTPZJ3Mi4N/czYjpU3HDD9FF8rCFX5yxsCRFWu2Mkf4BWqSdzOQY56yupgEn5OOro563wZ3/xQxgbjv37NoWRmZCAQPwKzI87lI/CzBR02AlZB6+SXgS3TNkbtMdF2EtgZA6GgkSyjMNowyP/kymQXYYBEBpcAF7w3j3HJ7nBPSSxc+9V7c0rt1qAQ65yjgvgc7kUYUojvWeBKcoqJ/3y6sORNk/Pv79fsqkX4GbVlOySFJaQFjtXrO5bRzxWfE03ZGvjCi3xbwi89DTlDQn+aqty3MCIc7AH+ZL3z+22zEnkfZ1Ki0Z/kBCcVDrAUU7eLbyY7ZSskjytqrsCayRxz8OVvDVxWHt+qXgUL3ffoheZFtxizaJ/ZBACuj4greMtxDvdxQTidhlBu6kOwssJJg/BFFx0JEc0O3HPt3DGaARVgzudUsd9gNA=
