dist: trusty
language: node_js
node_js:
- '10'
before_install:
- npm install
deploy:
  app: cloudpt
  provider: heroku
  api_key:
    secure: T+T+M6BvMz/KPmRMKFuGZR01nlAD/7R7TiJ/5mT26zpg+w6v1QaF6kirqFtMJCXRcyWsUlRC/KE/Q271fbeaSPkfS/v5iSyFA1kBknx2D4XzGDokb+XFdkyptDeakpXCrXtLvsXoS82L4MyJmKkbq2FPqc9hTOoit6gVy9lvXo36JFJOb6f8xbndLHuYLM1fm5kjSagpSBuX0R/NeDqCGA7jFj7nUvyIPKz+w0dF9dOAjm+iEZowpqMEEMUdE/kmCgtDO+Ntb/6Z8/9jqdF/caqTmOgc5IdXqBEM0tr3VM6m4Ccosz8t8JZzuZ9VljXnbu9gJwx2lEi3CK2C8K/AJCUAJ59CGks6ucsz+YthakadY8BEF+CiqxyEquCqtqVnlCuXfNWrwYkwUgTJeF9n6M9zcozATUHqp6dyx7kkdMJqc8F17cih3kgGcX9f9Tuu2zGHxJgNbHvxHDngbPTf8jJUKsp7eIiutwKB1GLWa/6cCPw34RCVymPw6UobYscA2GAC/vJRMrTg1ohj+v66BWWfZ80CoHvNQlwBIxnEwYlb4tYwZpvzb8P+54PYtmQ3QvQbHKq4oDx49QJ920DS9o7BQwCUGm6opAU9JJ2Ng0St142jru/hx0C+2BVPaZKbYD9H4l47qla7Z/Xm2DE34aYsL8Ok9BKOEO3XnZELdUI=
