dist: trusty
language: node_js
node_js:
- '10'
before_install:
- npm install
deploy:
  app: cloudpt
  provider: heroku
  api_key:
    secure: QadCVB8ImlbfqCTIVjELuO5eGoUBg6gVU2/hFVmsQ8asjWMQi8htP0FXNRxqSpMU50XXBmxUAy1XdNtwYpqnsgWb64sBPghZ1uZ3eFed4+t0IQTCkmegsZxOJIrXqGSIbnqT2rUaOxqPaYt+gFEUP7jWpdDl6IDtrCzwjNX7yOPvbxKf+PX1ud7BqbtnhRNPLyXQBpqKm1MegfMXRi9100PKVF/f8DedMW6PgETFlqwm4Uv9V72ema0SqQzZy1sDG4dZfLXoxysCDosxUeeqqFZrjmdLDRHU74x1b26peZFJ9/ii9ULIrSmyUxbExH01kNkr/crqM60zgCgOeNEMEZhuSIQVXDdKFiqZfRbqQdzDgyjNsp/WJPdixHjR8AHIWbMBx/al8vN5Pj2qW6a27n7pbvsnUVoO7IYsA0n5FpPVuCmcByZqIlWFrKPB3bO9711B1tQ4ig7AvR6HLqwu/9YtzuIHtDqS9XdVwS91aOjS8f0/kus/9MxVQF/f+OXFmskdWddh4p3DcoG0KnswQIOLElv3ac0p/P04ZSCLr0kBCxhVQ76/janmzLm5wYfqRr9RUDl0Uq03dzecNMye2nF/PRHX+srrJY8Me44T3AmZEjWXSCk75qw/pfIOpQWt0Qwm2nUsAzLftlKpMmUXmoMWNAn29QAkpSOpc41GXtQ=
